mixin:
  client_id: "xxxx-xxxx-..."
  pin_token: "WoKxxxxxxxxxxxx...3Rwc="
  private_key: "-----BEGIN RSA PRIVATE KEY-----\r\nxxxxxxxxx\r\n-----END RSA PRIVATE KEY-----\r\n"
  session_id: "xxxx-xxxx-..."

db:
  dsn: USER:PASSWORD@tcp(IP:PORT)/DB_NAME?parseTime=true

oracle:
  request_timeout: 3s
  approve_threshold: 2
  price_delta: 0.01

worker:
  term_timeout: 5s

debug: true
